/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class JsonVXMetricUserGroupCount {
  @SerializedName("groupCount")
  private BigDecimal groupCount = null;

  @SerializedName("userCountOfUserRole")
  private BigDecimal userCountOfUserRole = null;

  @SerializedName("userCountOfKeyAdminRole")
  private BigDecimal userCountOfKeyAdminRole = null;

  @SerializedName("userCountOfSysAdminRole")
  private BigDecimal userCountOfSysAdminRole = null;

  @SerializedName("userCountOfKeyadminAuditorRole")
  private BigDecimal userCountOfKeyadminAuditorRole = null;

  @SerializedName("userCountOfSysAdminAuditorRole")
  private BigDecimal userCountOfSysAdminAuditorRole = null;

  @SerializedName("userTotalCount")
  private BigDecimal userTotalCount = null;

  public JsonVXMetricUserGroupCount groupCount(BigDecimal groupCount) {
    this.groupCount = groupCount;
    return this;
  }

   /**
   * 
   * @return groupCount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getGroupCount() {
    return groupCount;
  }

  public void setGroupCount(BigDecimal groupCount) {
    this.groupCount = groupCount;
  }

  public JsonVXMetricUserGroupCount userCountOfUserRole(BigDecimal userCountOfUserRole) {
    this.userCountOfUserRole = userCountOfUserRole;
    return this;
  }

   /**
   * 
   * @return userCountOfUserRole
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getUserCountOfUserRole() {
    return userCountOfUserRole;
  }

  public void setUserCountOfUserRole(BigDecimal userCountOfUserRole) {
    this.userCountOfUserRole = userCountOfUserRole;
  }

  public JsonVXMetricUserGroupCount userCountOfKeyAdminRole(BigDecimal userCountOfKeyAdminRole) {
    this.userCountOfKeyAdminRole = userCountOfKeyAdminRole;
    return this;
  }

   /**
   * 
   * @return userCountOfKeyAdminRole
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getUserCountOfKeyAdminRole() {
    return userCountOfKeyAdminRole;
  }

  public void setUserCountOfKeyAdminRole(BigDecimal userCountOfKeyAdminRole) {
    this.userCountOfKeyAdminRole = userCountOfKeyAdminRole;
  }

  public JsonVXMetricUserGroupCount userCountOfSysAdminRole(BigDecimal userCountOfSysAdminRole) {
    this.userCountOfSysAdminRole = userCountOfSysAdminRole;
    return this;
  }

   /**
   * 
   * @return userCountOfSysAdminRole
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getUserCountOfSysAdminRole() {
    return userCountOfSysAdminRole;
  }

  public void setUserCountOfSysAdminRole(BigDecimal userCountOfSysAdminRole) {
    this.userCountOfSysAdminRole = userCountOfSysAdminRole;
  }

  public JsonVXMetricUserGroupCount userCountOfKeyadminAuditorRole(BigDecimal userCountOfKeyadminAuditorRole) {
    this.userCountOfKeyadminAuditorRole = userCountOfKeyadminAuditorRole;
    return this;
  }

   /**
   * 
   * @return userCountOfKeyadminAuditorRole
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getUserCountOfKeyadminAuditorRole() {
    return userCountOfKeyadminAuditorRole;
  }

  public void setUserCountOfKeyadminAuditorRole(BigDecimal userCountOfKeyadminAuditorRole) {
    this.userCountOfKeyadminAuditorRole = userCountOfKeyadminAuditorRole;
  }

  public JsonVXMetricUserGroupCount userCountOfSysAdminAuditorRole(BigDecimal userCountOfSysAdminAuditorRole) {
    this.userCountOfSysAdminAuditorRole = userCountOfSysAdminAuditorRole;
    return this;
  }

   /**
   * 
   * @return userCountOfSysAdminAuditorRole
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getUserCountOfSysAdminAuditorRole() {
    return userCountOfSysAdminAuditorRole;
  }

  public void setUserCountOfSysAdminAuditorRole(BigDecimal userCountOfSysAdminAuditorRole) {
    this.userCountOfSysAdminAuditorRole = userCountOfSysAdminAuditorRole;
  }

  public JsonVXMetricUserGroupCount userTotalCount(BigDecimal userTotalCount) {
    this.userTotalCount = userTotalCount;
    return this;
  }

   /**
   * 
   * @return userTotalCount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getUserTotalCount() {
    return userTotalCount;
  }

  public void setUserTotalCount(BigDecimal userTotalCount) {
    this.userTotalCount = userTotalCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonVXMetricUserGroupCount jsonVXMetricUserGroupCount = (JsonVXMetricUserGroupCount) o;
    return Objects.equals(this.groupCount, jsonVXMetricUserGroupCount.groupCount) &&
        Objects.equals(this.userCountOfUserRole, jsonVXMetricUserGroupCount.userCountOfUserRole) &&
        Objects.equals(this.userCountOfKeyAdminRole, jsonVXMetricUserGroupCount.userCountOfKeyAdminRole) &&
        Objects.equals(this.userCountOfSysAdminRole, jsonVXMetricUserGroupCount.userCountOfSysAdminRole) &&
        Objects.equals(this.userCountOfKeyadminAuditorRole, jsonVXMetricUserGroupCount.userCountOfKeyadminAuditorRole) &&
        Objects.equals(this.userCountOfSysAdminAuditorRole, jsonVXMetricUserGroupCount.userCountOfSysAdminAuditorRole) &&
        Objects.equals(this.userTotalCount, jsonVXMetricUserGroupCount.userTotalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupCount, userCountOfUserRole, userCountOfKeyAdminRole, userCountOfSysAdminRole, userCountOfKeyadminAuditorRole, userCountOfSysAdminAuditorRole, userTotalCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonVXMetricUserGroupCount {\n");
    
    sb.append("    groupCount: ").append(toIndentedString(groupCount)).append("\n");
    sb.append("    userCountOfUserRole: ").append(toIndentedString(userCountOfUserRole)).append("\n");
    sb.append("    userCountOfKeyAdminRole: ").append(toIndentedString(userCountOfKeyAdminRole)).append("\n");
    sb.append("    userCountOfSysAdminRole: ").append(toIndentedString(userCountOfSysAdminRole)).append("\n");
    sb.append("    userCountOfKeyadminAuditorRole: ").append(toIndentedString(userCountOfKeyadminAuditorRole)).append("\n");
    sb.append("    userCountOfSysAdminAuditorRole: ").append(toIndentedString(userCountOfSysAdminAuditorRole)).append("\n");
    sb.append("    userTotalCount: ").append(toIndentedString(userTotalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

