/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class JsonXXTagChangeLog {
  @SerializedName("myClassType")
  private Integer myClassType = null;

  @SerializedName("myDisplayValue")
  private String myDisplayValue = null;

  @SerializedName("id")
  private BigDecimal id = null;

  @SerializedName("createTime")
  private BigDecimal createTime = null;

  @SerializedName("serviceId")
  private BigDecimal serviceId = null;

  @SerializedName("changeType")
  private BigDecimal changeType = null;

  @SerializedName("serviceTagsVersion")
  private BigDecimal serviceTagsVersion = null;

  @SerializedName("serviceResourceId")
  private BigDecimal serviceResourceId = null;

  @SerializedName("tagId")
  private BigDecimal tagId = null;

  public JsonXXTagChangeLog myClassType(Integer myClassType) {
    this.myClassType = myClassType;
    return this;
  }

   /**
   * 
   * @return myClassType
  **/
  @ApiModelProperty(value = "")
  public Integer getMyClassType() {
    return myClassType;
  }

  public void setMyClassType(Integer myClassType) {
    this.myClassType = myClassType;
  }

  public JsonXXTagChangeLog myDisplayValue(String myDisplayValue) {
    this.myDisplayValue = myDisplayValue;
    return this;
  }

   /**
   * 
   * @return myDisplayValue
  **/
  @ApiModelProperty(value = "")
  public String getMyDisplayValue() {
    return myDisplayValue;
  }

  public void setMyDisplayValue(String myDisplayValue) {
    this.myDisplayValue = myDisplayValue;
  }

  public JsonXXTagChangeLog id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public JsonXXTagChangeLog createTime(BigDecimal createTime) {
    this.createTime = createTime;
    return this;
  }

   /**
   * 
   * @return createTime
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getCreateTime() {
    return createTime;
  }

  public void setCreateTime(BigDecimal createTime) {
    this.createTime = createTime;
  }

  public JsonXXTagChangeLog serviceId(BigDecimal serviceId) {
    this.serviceId = serviceId;
    return this;
  }

   /**
   * 
   * @return serviceId
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getServiceId() {
    return serviceId;
  }

  public void setServiceId(BigDecimal serviceId) {
    this.serviceId = serviceId;
  }

  public JsonXXTagChangeLog changeType(BigDecimal changeType) {
    this.changeType = changeType;
    return this;
  }

   /**
   * 
   * @return changeType
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getChangeType() {
    return changeType;
  }

  public void setChangeType(BigDecimal changeType) {
    this.changeType = changeType;
  }

  public JsonXXTagChangeLog serviceTagsVersion(BigDecimal serviceTagsVersion) {
    this.serviceTagsVersion = serviceTagsVersion;
    return this;
  }

   /**
   * 
   * @return serviceTagsVersion
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getServiceTagsVersion() {
    return serviceTagsVersion;
  }

  public void setServiceTagsVersion(BigDecimal serviceTagsVersion) {
    this.serviceTagsVersion = serviceTagsVersion;
  }

  public JsonXXTagChangeLog serviceResourceId(BigDecimal serviceResourceId) {
    this.serviceResourceId = serviceResourceId;
    return this;
  }

   /**
   * 
   * @return serviceResourceId
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getServiceResourceId() {
    return serviceResourceId;
  }

  public void setServiceResourceId(BigDecimal serviceResourceId) {
    this.serviceResourceId = serviceResourceId;
  }

  public JsonXXTagChangeLog tagId(BigDecimal tagId) {
    this.tagId = tagId;
    return this;
  }

   /**
   * 
   * @return tagId
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getTagId() {
    return tagId;
  }

  public void setTagId(BigDecimal tagId) {
    this.tagId = tagId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonXXTagChangeLog jsonXXTagChangeLog = (JsonXXTagChangeLog) o;
    return Objects.equals(this.myClassType, jsonXXTagChangeLog.myClassType) &&
        Objects.equals(this.myDisplayValue, jsonXXTagChangeLog.myDisplayValue) &&
        Objects.equals(this.id, jsonXXTagChangeLog.id) &&
        Objects.equals(this.createTime, jsonXXTagChangeLog.createTime) &&
        Objects.equals(this.serviceId, jsonXXTagChangeLog.serviceId) &&
        Objects.equals(this.changeType, jsonXXTagChangeLog.changeType) &&
        Objects.equals(this.serviceTagsVersion, jsonXXTagChangeLog.serviceTagsVersion) &&
        Objects.equals(this.serviceResourceId, jsonXXTagChangeLog.serviceResourceId) &&
        Objects.equals(this.tagId, jsonXXTagChangeLog.tagId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(myClassType, myDisplayValue, id, createTime, serviceId, changeType, serviceTagsVersion, serviceResourceId, tagId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonXXTagChangeLog {\n");
    
    sb.append("    myClassType: ").append(toIndentedString(myClassType)).append("\n");
    sb.append("    myDisplayValue: ").append(toIndentedString(myDisplayValue)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    serviceId: ").append(toIndentedString(serviceId)).append("\n");
    sb.append("    changeType: ").append(toIndentedString(changeType)).append("\n");
    sb.append("    serviceTagsVersion: ").append(toIndentedString(serviceTagsVersion)).append("\n");
    sb.append("    serviceResourceId: ").append(toIndentedString(serviceResourceId)).append("\n");
    sb.append("    tagId: ").append(toIndentedString(tagId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

