/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.JsonViewBaseBean;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class JsonVXMessage extends JsonViewBaseBean {
  @SerializedName("name")
  private String name = null;

  @SerializedName("rbKey")
  private String rbKey = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("objectId")
  private BigDecimal objectId = null;

  @SerializedName("fieldName")
  private String fieldName = null;

  @SerializedName("myClassType")
  private Integer myClassType = null;

  public JsonVXMessage name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;name&lt;/b&gt;
   * @return name
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>name</b>")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public JsonVXMessage rbKey(String rbKey) {
    this.rbKey = rbKey;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;rbKey&lt;/b&gt;
   * @return rbKey
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>rbKey</b>")
  public String getRbKey() {
    return rbKey;
  }

  public void setRbKey(String rbKey) {
    this.rbKey = rbKey;
  }

  public JsonVXMessage message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;message&lt;/b&gt;
   * @return message
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>message</b>")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public JsonVXMessage objectId(BigDecimal objectId) {
    this.objectId = objectId;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;objectId&lt;/b&gt;
   * @return objectId
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>objectId</b>")
  public BigDecimal getObjectId() {
    return objectId;
  }

  public void setObjectId(BigDecimal objectId) {
    this.objectId = objectId;
  }

  public JsonVXMessage fieldName(String fieldName) {
    this.fieldName = fieldName;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;fieldName&lt;/b&gt;
   * @return fieldName
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>fieldName</b>")
  public String getFieldName() {
    return fieldName;
  }

  public void setFieldName(String fieldName) {
    this.fieldName = fieldName;
  }

  public JsonVXMessage myClassType(Integer myClassType) {
    this.myClassType = myClassType;
    return this;
  }

   /**
   * 
   * @return myClassType
  **/
  @ApiModelProperty(value = "")
  public Integer getMyClassType() {
    return myClassType;
  }

  public void setMyClassType(Integer myClassType) {
    this.myClassType = myClassType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonVXMessage jsonVXMessage = (JsonVXMessage) o;
    return Objects.equals(this.name, jsonVXMessage.name) &&
        Objects.equals(this.rbKey, jsonVXMessage.rbKey) &&
        Objects.equals(this.message, jsonVXMessage.message) &&
        Objects.equals(this.objectId, jsonVXMessage.objectId) &&
        Objects.equals(this.fieldName, jsonVXMessage.fieldName) &&
        Objects.equals(this.myClassType, jsonVXMessage.myClassType) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, rbKey, message, objectId, fieldName, myClassType, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonVXMessage {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    rbKey: ").append(toIndentedString(rbKey)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    objectId: ").append(toIndentedString(objectId)).append("\n");
    sb.append("    fieldName: ").append(toIndentedString(fieldName)).append("\n");
    sb.append("    myClassType: ").append(toIndentedString(myClassType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

