/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.JsonVXDataObject;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class JsonVXAccessAudit extends JsonVXDataObject {
  @SerializedName("auditType")
  private Integer auditType = null;

  @SerializedName("accessResult")
  private Integer accessResult = null;

  @SerializedName("accessType")
  private String accessType = null;

  @SerializedName("aclEnforcer")
  private String aclEnforcer = null;

  @SerializedName("agentId")
  private String agentId = null;

  @SerializedName("clientIP")
  private String clientIP = null;

  @SerializedName("clientType")
  private String clientType = null;

  @SerializedName("policyId")
  private Long policyId = null;

  @SerializedName("repoName")
  private String repoName = null;

  @SerializedName("repoDisplayName")
  private String repoDisplayName = null;

  @SerializedName("repoType")
  private Integer repoType = null;

  @SerializedName("serviceType")
  private String serviceType = null;

  @SerializedName("serviceTypeDisplayName")
  private String serviceTypeDisplayName = null;

  @SerializedName("resultReason")
  private String resultReason = null;

  @SerializedName("sessionId")
  private String sessionId = null;

  @SerializedName("eventTime")
  private BigDecimal eventTime = null;

  @SerializedName("requestUser")
  private String requestUser = null;

  @SerializedName("action")
  private String action = null;

  @SerializedName("requestData")
  private String requestData = null;

  @SerializedName("resourcePath")
  private String resourcePath = null;

  @SerializedName("resourceType")
  private String resourceType = null;

  @SerializedName("sequenceNumber")
  private Long sequenceNumber = null;

  @SerializedName("eventCount")
  private Long eventCount = null;

  @SerializedName("eventDuration")
  private Long eventDuration = null;

  @SerializedName("tags")
  private String tags = null;

  @SerializedName("clusterName")
  private String clusterName = null;

  @SerializedName("myClassType")
  private Integer myClassType = null;

  @SerializedName("zoneName")
  private String zoneName = null;

  @SerializedName("agentHost")
  private String agentHost = null;

  @SerializedName("policyVersion")
  private BigDecimal policyVersion = null;

  @SerializedName("eventId")
  private String eventId = null;

  public JsonVXAccessAudit auditType(Integer auditType) {
    this.auditType = auditType;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;auditType&lt;/b&gt;
   * @return auditType
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>auditType</b>")
  public Integer getAuditType() {
    return auditType;
  }

  public void setAuditType(Integer auditType) {
    this.auditType = auditType;
  }

  public JsonVXAccessAudit accessResult(Integer accessResult) {
    this.accessResult = accessResult;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;accessResult&lt;/b&gt;
   * @return accessResult
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>accessResult</b>")
  public Integer getAccessResult() {
    return accessResult;
  }

  public void setAccessResult(Integer accessResult) {
    this.accessResult = accessResult;
  }

  public JsonVXAccessAudit accessType(String accessType) {
    this.accessType = accessType;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;accessType&lt;/b&gt;
   * @return accessType
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>accessType</b>")
  public String getAccessType() {
    return accessType;
  }

  public void setAccessType(String accessType) {
    this.accessType = accessType;
  }

  public JsonVXAccessAudit aclEnforcer(String aclEnforcer) {
    this.aclEnforcer = aclEnforcer;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;aclEnforcer&lt;/b&gt;
   * @return aclEnforcer
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>aclEnforcer</b>")
  public String getAclEnforcer() {
    return aclEnforcer;
  }

  public void setAclEnforcer(String aclEnforcer) {
    this.aclEnforcer = aclEnforcer;
  }

  public JsonVXAccessAudit agentId(String agentId) {
    this.agentId = agentId;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;agentId&lt;/b&gt;
   * @return agentId
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>agentId</b>")
  public String getAgentId() {
    return agentId;
  }

  public void setAgentId(String agentId) {
    this.agentId = agentId;
  }

  public JsonVXAccessAudit clientIP(String clientIP) {
    this.clientIP = clientIP;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;clientIP&lt;/b&gt;
   * @return clientIP
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>clientIP</b>")
  public String getClientIP() {
    return clientIP;
  }

  public void setClientIP(String clientIP) {
    this.clientIP = clientIP;
  }

  public JsonVXAccessAudit clientType(String clientType) {
    this.clientType = clientType;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;clientType&lt;/b&gt;
   * @return clientType
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>clientType</b>")
  public String getClientType() {
    return clientType;
  }

  public void setClientType(String clientType) {
    this.clientType = clientType;
  }

  public JsonVXAccessAudit policyId(Long policyId) {
    this.policyId = policyId;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;policyId&lt;/b&gt;
   * @return policyId
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>policyId</b>")
  public Long getPolicyId() {
    return policyId;
  }

  public void setPolicyId(Long policyId) {
    this.policyId = policyId;
  }

  public JsonVXAccessAudit repoName(String repoName) {
    this.repoName = repoName;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;repoName&lt;/b&gt;
   * @return repoName
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>repoName</b>")
  public String getRepoName() {
    return repoName;
  }

  public void setRepoName(String repoName) {
    this.repoName = repoName;
  }

  public JsonVXAccessAudit repoDisplayName(String repoDisplayName) {
    this.repoDisplayName = repoDisplayName;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;repoDisplayName&lt;/b&gt;
   * @return repoDisplayName
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>repoDisplayName</b>")
  public String getRepoDisplayName() {
    return repoDisplayName;
  }

  public void setRepoDisplayName(String repoDisplayName) {
    this.repoDisplayName = repoDisplayName;
  }

  public JsonVXAccessAudit repoType(Integer repoType) {
    this.repoType = repoType;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;repoType&lt;/b&gt;
   * @return repoType
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>repoType</b>")
  public Integer getRepoType() {
    return repoType;
  }

  public void setRepoType(Integer repoType) {
    this.repoType = repoType;
  }

  public JsonVXAccessAudit serviceType(String serviceType) {
    this.serviceType = serviceType;
    return this;
  }

   /**
   * 
   * @return serviceType
  **/
  @ApiModelProperty(value = "")
  public String getServiceType() {
    return serviceType;
  }

  public void setServiceType(String serviceType) {
    this.serviceType = serviceType;
  }

  public JsonVXAccessAudit serviceTypeDisplayName(String serviceTypeDisplayName) {
    this.serviceTypeDisplayName = serviceTypeDisplayName;
    return this;
  }

   /**
   * 
   * @return serviceTypeDisplayName
  **/
  @ApiModelProperty(value = "")
  public String getServiceTypeDisplayName() {
    return serviceTypeDisplayName;
  }

  public void setServiceTypeDisplayName(String serviceTypeDisplayName) {
    this.serviceTypeDisplayName = serviceTypeDisplayName;
  }

  public JsonVXAccessAudit resultReason(String resultReason) {
    this.resultReason = resultReason;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;resultReason&lt;/b&gt;
   * @return resultReason
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>resultReason</b>")
  public String getResultReason() {
    return resultReason;
  }

  public void setResultReason(String resultReason) {
    this.resultReason = resultReason;
  }

  public JsonVXAccessAudit sessionId(String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;sessionId&lt;/b&gt;
   * @return sessionId
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>sessionId</b>")
  public String getSessionId() {
    return sessionId;
  }

  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }

  public JsonVXAccessAudit eventTime(BigDecimal eventTime) {
    this.eventTime = eventTime;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;eventTime&lt;/b&gt;
   * @return eventTime
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>eventTime</b>")
  public BigDecimal getEventTime() {
    return eventTime;
  }

  public void setEventTime(BigDecimal eventTime) {
    this.eventTime = eventTime;
  }

  public JsonVXAccessAudit requestUser(String requestUser) {
    this.requestUser = requestUser;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;requestUser&lt;/b&gt;
   * @return requestUser
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>requestUser</b>")
  public String getRequestUser() {
    return requestUser;
  }

  public void setRequestUser(String requestUser) {
    this.requestUser = requestUser;
  }

  public JsonVXAccessAudit action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;action&lt;/b&gt;
   * @return action
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>action</b>")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public JsonVXAccessAudit requestData(String requestData) {
    this.requestData = requestData;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;requestData&lt;/b&gt;
   * @return requestData
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>requestData</b>")
  public String getRequestData() {
    return requestData;
  }

  public void setRequestData(String requestData) {
    this.requestData = requestData;
  }

  public JsonVXAccessAudit resourcePath(String resourcePath) {
    this.resourcePath = resourcePath;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;resourcePath&lt;/b&gt;
   * @return resourcePath
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>resourcePath</b>")
  public String getResourcePath() {
    return resourcePath;
  }

  public void setResourcePath(String resourcePath) {
    this.resourcePath = resourcePath;
  }

  public JsonVXAccessAudit resourceType(String resourceType) {
    this.resourceType = resourceType;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;resourceType&lt;/b&gt;
   * @return resourceType
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>resourceType</b>")
  public String getResourceType() {
    return resourceType;
  }

  public void setResourceType(String resourceType) {
    this.resourceType = resourceType;
  }

  public JsonVXAccessAudit sequenceNumber(Long sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
    return this;
  }

   /**
   * 
   * @return sequenceNumber
  **/
  @ApiModelProperty(value = "")
  public Long getSequenceNumber() {
    return sequenceNumber;
  }

  public void setSequenceNumber(Long sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
  }

  public JsonVXAccessAudit eventCount(Long eventCount) {
    this.eventCount = eventCount;
    return this;
  }

   /**
   * 
   * @return eventCount
  **/
  @ApiModelProperty(value = "")
  public Long getEventCount() {
    return eventCount;
  }

  public void setEventCount(Long eventCount) {
    this.eventCount = eventCount;
  }

  public JsonVXAccessAudit eventDuration(Long eventDuration) {
    this.eventDuration = eventDuration;
    return this;
  }

   /**
   * 
   * @return eventDuration
  **/
  @ApiModelProperty(value = "")
  public Long getEventDuration() {
    return eventDuration;
  }

  public void setEventDuration(Long eventDuration) {
    this.eventDuration = eventDuration;
  }

  public JsonVXAccessAudit tags(String tags) {
    this.tags = tags;
    return this;
  }

   /**
   * 
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public String getTags() {
    return tags;
  }

  public void setTags(String tags) {
    this.tags = tags;
  }

  public JsonVXAccessAudit clusterName(String clusterName) {
    this.clusterName = clusterName;
    return this;
  }

   /**
   * 
   * @return clusterName
  **/
  @ApiModelProperty(value = "")
  public String getClusterName() {
    return clusterName;
  }

  public void setClusterName(String clusterName) {
    this.clusterName = clusterName;
  }

  public JsonVXAccessAudit myClassType(Integer myClassType) {
    this.myClassType = myClassType;
    return this;
  }

   /**
   * 
   * @return myClassType
  **/
  @ApiModelProperty(value = "")
  public Integer getMyClassType() {
    return myClassType;
  }

  public void setMyClassType(Integer myClassType) {
    this.myClassType = myClassType;
  }

  public JsonVXAccessAudit zoneName(String zoneName) {
    this.zoneName = zoneName;
    return this;
  }

   /**
   * 
   * @return zoneName
  **/
  @ApiModelProperty(value = "")
  public String getZoneName() {
    return zoneName;
  }

  public void setZoneName(String zoneName) {
    this.zoneName = zoneName;
  }

  public JsonVXAccessAudit agentHost(String agentHost) {
    this.agentHost = agentHost;
    return this;
  }

   /**
   * 
   * @return agentHost
  **/
  @ApiModelProperty(value = "")
  public String getAgentHost() {
    return agentHost;
  }

  public void setAgentHost(String agentHost) {
    this.agentHost = agentHost;
  }

  public JsonVXAccessAudit policyVersion(BigDecimal policyVersion) {
    this.policyVersion = policyVersion;
    return this;
  }

   /**
   * 
   * @return policyVersion
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getPolicyVersion() {
    return policyVersion;
  }

  public void setPolicyVersion(BigDecimal policyVersion) {
    this.policyVersion = policyVersion;
  }

  public JsonVXAccessAudit eventId(String eventId) {
    this.eventId = eventId;
    return this;
  }

   /**
   * 
   * @return eventId
  **/
  @ApiModelProperty(value = "")
  public String getEventId() {
    return eventId;
  }

  public void setEventId(String eventId) {
    this.eventId = eventId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonVXAccessAudit jsonVXAccessAudit = (JsonVXAccessAudit) o;
    return Objects.equals(this.auditType, jsonVXAccessAudit.auditType) &&
        Objects.equals(this.accessResult, jsonVXAccessAudit.accessResult) &&
        Objects.equals(this.accessType, jsonVXAccessAudit.accessType) &&
        Objects.equals(this.aclEnforcer, jsonVXAccessAudit.aclEnforcer) &&
        Objects.equals(this.agentId, jsonVXAccessAudit.agentId) &&
        Objects.equals(this.clientIP, jsonVXAccessAudit.clientIP) &&
        Objects.equals(this.clientType, jsonVXAccessAudit.clientType) &&
        Objects.equals(this.policyId, jsonVXAccessAudit.policyId) &&
        Objects.equals(this.repoName, jsonVXAccessAudit.repoName) &&
        Objects.equals(this.repoDisplayName, jsonVXAccessAudit.repoDisplayName) &&
        Objects.equals(this.repoType, jsonVXAccessAudit.repoType) &&
        Objects.equals(this.serviceType, jsonVXAccessAudit.serviceType) &&
        Objects.equals(this.serviceTypeDisplayName, jsonVXAccessAudit.serviceTypeDisplayName) &&
        Objects.equals(this.resultReason, jsonVXAccessAudit.resultReason) &&
        Objects.equals(this.sessionId, jsonVXAccessAudit.sessionId) &&
        Objects.equals(this.eventTime, jsonVXAccessAudit.eventTime) &&
        Objects.equals(this.requestUser, jsonVXAccessAudit.requestUser) &&
        Objects.equals(this.action, jsonVXAccessAudit.action) &&
        Objects.equals(this.requestData, jsonVXAccessAudit.requestData) &&
        Objects.equals(this.resourcePath, jsonVXAccessAudit.resourcePath) &&
        Objects.equals(this.resourceType, jsonVXAccessAudit.resourceType) &&
        Objects.equals(this.sequenceNumber, jsonVXAccessAudit.sequenceNumber) &&
        Objects.equals(this.eventCount, jsonVXAccessAudit.eventCount) &&
        Objects.equals(this.eventDuration, jsonVXAccessAudit.eventDuration) &&
        Objects.equals(this.tags, jsonVXAccessAudit.tags) &&
        Objects.equals(this.clusterName, jsonVXAccessAudit.clusterName) &&
        Objects.equals(this.myClassType, jsonVXAccessAudit.myClassType) &&
        Objects.equals(this.zoneName, jsonVXAccessAudit.zoneName) &&
        Objects.equals(this.agentHost, jsonVXAccessAudit.agentHost) &&
        Objects.equals(this.policyVersion, jsonVXAccessAudit.policyVersion) &&
        Objects.equals(this.eventId, jsonVXAccessAudit.eventId) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(auditType, accessResult, accessType, aclEnforcer, agentId, clientIP, clientType, policyId, repoName, repoDisplayName, repoType, serviceType, serviceTypeDisplayName, resultReason, sessionId, eventTime, requestUser, action, requestData, resourcePath, resourceType, sequenceNumber, eventCount, eventDuration, tags, clusterName, myClassType, zoneName, agentHost, policyVersion, eventId, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonVXAccessAudit {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    auditType: ").append(toIndentedString(auditType)).append("\n");
    sb.append("    accessResult: ").append(toIndentedString(accessResult)).append("\n");
    sb.append("    accessType: ").append(toIndentedString(accessType)).append("\n");
    sb.append("    aclEnforcer: ").append(toIndentedString(aclEnforcer)).append("\n");
    sb.append("    agentId: ").append(toIndentedString(agentId)).append("\n");
    sb.append("    clientIP: ").append(toIndentedString(clientIP)).append("\n");
    sb.append("    clientType: ").append(toIndentedString(clientType)).append("\n");
    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("    repoName: ").append(toIndentedString(repoName)).append("\n");
    sb.append("    repoDisplayName: ").append(toIndentedString(repoDisplayName)).append("\n");
    sb.append("    repoType: ").append(toIndentedString(repoType)).append("\n");
    sb.append("    serviceType: ").append(toIndentedString(serviceType)).append("\n");
    sb.append("    serviceTypeDisplayName: ").append(toIndentedString(serviceTypeDisplayName)).append("\n");
    sb.append("    resultReason: ").append(toIndentedString(resultReason)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    eventTime: ").append(toIndentedString(eventTime)).append("\n");
    sb.append("    requestUser: ").append(toIndentedString(requestUser)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    requestData: ").append(toIndentedString(requestData)).append("\n");
    sb.append("    resourcePath: ").append(toIndentedString(resourcePath)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    sequenceNumber: ").append(toIndentedString(sequenceNumber)).append("\n");
    sb.append("    eventCount: ").append(toIndentedString(eventCount)).append("\n");
    sb.append("    eventDuration: ").append(toIndentedString(eventDuration)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    clusterName: ").append(toIndentedString(clusterName)).append("\n");
    sb.append("    myClassType: ").append(toIndentedString(myClassType)).append("\n");
    sb.append("    zoneName: ").append(toIndentedString(zoneName)).append("\n");
    sb.append("    agentHost: ").append(toIndentedString(agentHost)).append("\n");
    sb.append("    policyVersion: ").append(toIndentedString(policyVersion)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

