/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class JsonXXRMSResourceMapping {
  @SerializedName("id")
  private BigDecimal id = null;

  @SerializedName("changeTimestamp")
  private BigDecimal changeTimestamp = null;

  @SerializedName("hlResourceId")
  private BigDecimal hlResourceId = null;

  @SerializedName("llResourceId")
  private BigDecimal llResourceId = null;

  @SerializedName("myClassType")
  private Integer myClassType = null;

  public JsonXXRMSResourceMapping id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public JsonXXRMSResourceMapping changeTimestamp(BigDecimal changeTimestamp) {
    this.changeTimestamp = changeTimestamp;
    return this;
  }

   /**
   * 
   * @return changeTimestamp
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getChangeTimestamp() {
    return changeTimestamp;
  }

  public void setChangeTimestamp(BigDecimal changeTimestamp) {
    this.changeTimestamp = changeTimestamp;
  }

  public JsonXXRMSResourceMapping hlResourceId(BigDecimal hlResourceId) {
    this.hlResourceId = hlResourceId;
    return this;
  }

   /**
   * 
   * @return hlResourceId
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getHlResourceId() {
    return hlResourceId;
  }

  public void setHlResourceId(BigDecimal hlResourceId) {
    this.hlResourceId = hlResourceId;
  }

  public JsonXXRMSResourceMapping llResourceId(BigDecimal llResourceId) {
    this.llResourceId = llResourceId;
    return this;
  }

   /**
   * 
   * @return llResourceId
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getLlResourceId() {
    return llResourceId;
  }

  public void setLlResourceId(BigDecimal llResourceId) {
    this.llResourceId = llResourceId;
  }

  public JsonXXRMSResourceMapping myClassType(Integer myClassType) {
    this.myClassType = myClassType;
    return this;
  }

   /**
   * 
   * @return myClassType
  **/
  @ApiModelProperty(value = "")
  public Integer getMyClassType() {
    return myClassType;
  }

  public void setMyClassType(Integer myClassType) {
    this.myClassType = myClassType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonXXRMSResourceMapping jsonXXRMSResourceMapping = (JsonXXRMSResourceMapping) o;
    return Objects.equals(this.id, jsonXXRMSResourceMapping.id) &&
        Objects.equals(this.changeTimestamp, jsonXXRMSResourceMapping.changeTimestamp) &&
        Objects.equals(this.hlResourceId, jsonXXRMSResourceMapping.hlResourceId) &&
        Objects.equals(this.llResourceId, jsonXXRMSResourceMapping.llResourceId) &&
        Objects.equals(this.myClassType, jsonXXRMSResourceMapping.myClassType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, changeTimestamp, hlResourceId, llResourceId, myClassType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonXXRMSResourceMapping {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    changeTimestamp: ").append(toIndentedString(changeTimestamp)).append("\n");
    sb.append("    hlResourceId: ").append(toIndentedString(hlResourceId)).append("\n");
    sb.append("    llResourceId: ").append(toIndentedString(llResourceId)).append("\n");
    sb.append("    myClassType: ").append(toIndentedString(myClassType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

