/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class JsonMessage {
  @SerializedName("fieldName")
  private String fieldName = null;

  @SerializedName("objectId")
  private BigDecimal objectId = null;

  @SerializedName("rbKey")
  private String rbKey = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("name")
  private String name = null;

  public JsonMessage fieldName(String fieldName) {
    this.fieldName = fieldName;
    return this;
  }

   /**
   * 
   * @return fieldName
  **/
  @ApiModelProperty(value = "")
  public String getFieldName() {
    return fieldName;
  }

  public void setFieldName(String fieldName) {
    this.fieldName = fieldName;
  }

  public JsonMessage objectId(BigDecimal objectId) {
    this.objectId = objectId;
    return this;
  }

   /**
   * 
   * @return objectId
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getObjectId() {
    return objectId;
  }

  public void setObjectId(BigDecimal objectId) {
    this.objectId = objectId;
  }

  public JsonMessage rbKey(String rbKey) {
    this.rbKey = rbKey;
    return this;
  }

   /**
   * 
   * @return rbKey
  **/
  @ApiModelProperty(value = "")
  public String getRbKey() {
    return rbKey;
  }

  public void setRbKey(String rbKey) {
    this.rbKey = rbKey;
  }

  public JsonMessage message(String message) {
    this.message = message;
    return this;
  }

   /**
   * 
   * @return message
  **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public JsonMessage name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonMessage jsonMessage = (JsonMessage) o;
    return Objects.equals(this.fieldName, jsonMessage.fieldName) &&
        Objects.equals(this.objectId, jsonMessage.objectId) &&
        Objects.equals(this.rbKey, jsonMessage.rbKey) &&
        Objects.equals(this.message, jsonMessage.message) &&
        Objects.equals(this.name, jsonMessage.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldName, objectId, rbKey, message, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonMessage {\n");
    
    sb.append("    fieldName: ").append(toIndentedString(fieldName)).append("\n");
    sb.append("    objectId: ").append(toIndentedString(objectId)).append("\n");
    sb.append("    rbKey: ").append(toIndentedString(rbKey)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

