/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.JsonXXDBBase;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class JsonXXPolicyItem extends JsonXXDBBase {
  @SerializedName("id")
  private BigDecimal id = null;

  @SerializedName("GUID")
  private String GUID = null;

  @SerializedName("policyid")
  private BigDecimal policyid = null;

  @SerializedName("delegateAdmin")
  private Boolean delegateAdmin = null;

  @SerializedName("itemType")
  private BigDecimal itemType = null;

  @SerializedName("isEnabled")
  private Boolean isEnabled = null;

  @SerializedName("comments")
  private String comments = null;

  @SerializedName("order")
  private BigDecimal order = null;

  public JsonXXPolicyItem id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;id&lt;/b&gt;
   * @return id
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>id</b>")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public JsonXXPolicyItem GUID(String GUID) {
    this.GUID = GUID;
    return this;
  }

   /**
   * 
   * @return GUID
  **/
  @ApiModelProperty(value = "")
  public String getGUID() {
    return GUID;
  }

  public void setGUID(String GUID) {
    this.GUID = GUID;
  }

  public JsonXXPolicyItem policyid(BigDecimal policyid) {
    this.policyid = policyid;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;policyId&lt;/b&gt;
   * @return policyid
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>policyId</b>")
  public BigDecimal getPolicyid() {
    return policyid;
  }

  public void setPolicyid(BigDecimal policyid) {
    this.policyid = policyid;
  }

  public JsonXXPolicyItem delegateAdmin(Boolean delegateAdmin) {
    this.delegateAdmin = delegateAdmin;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;delegateAdmin&lt;/b&gt;
   * @return delegateAdmin
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>delegateAdmin</b>")
  public Boolean isDelegateAdmin() {
    return delegateAdmin;
  }

  public void setDelegateAdmin(Boolean delegateAdmin) {
    this.delegateAdmin = delegateAdmin;
  }

  public JsonXXPolicyItem itemType(BigDecimal itemType) {
    this.itemType = itemType;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;itemType&lt;/b&gt;
   * @return itemType
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>itemType</b>")
  public BigDecimal getItemType() {
    return itemType;
  }

  public void setItemType(BigDecimal itemType) {
    this.itemType = itemType;
  }

  public JsonXXPolicyItem isEnabled(Boolean isEnabled) {
    this.isEnabled = isEnabled;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;isEnabled&lt;/b&gt;
   * @return isEnabled
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>isEnabled</b>")
  public Boolean isIsEnabled() {
    return isEnabled;
  }

  public void setIsEnabled(Boolean isEnabled) {
    this.isEnabled = isEnabled;
  }

  public JsonXXPolicyItem comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;comments&lt;/b&gt;
   * @return comments
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>comments</b>")
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public JsonXXPolicyItem order(BigDecimal order) {
    this.order = order;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;order&lt;/b&gt;
   * @return order
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>order</b>")
  public BigDecimal getOrder() {
    return order;
  }

  public void setOrder(BigDecimal order) {
    this.order = order;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonXXPolicyItem jsonXXPolicyItem = (JsonXXPolicyItem) o;
    return Objects.equals(this.id, jsonXXPolicyItem.id) &&
        Objects.equals(this.GUID, jsonXXPolicyItem.GUID) &&
        Objects.equals(this.policyid, jsonXXPolicyItem.policyid) &&
        Objects.equals(this.delegateAdmin, jsonXXPolicyItem.delegateAdmin) &&
        Objects.equals(this.itemType, jsonXXPolicyItem.itemType) &&
        Objects.equals(this.isEnabled, jsonXXPolicyItem.isEnabled) &&
        Objects.equals(this.comments, jsonXXPolicyItem.comments) &&
        Objects.equals(this.order, jsonXXPolicyItem.order) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, GUID, policyid, delegateAdmin, itemType, isEnabled, comments, order, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonXXPolicyItem {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    GUID: ").append(toIndentedString(GUID)).append("\n");
    sb.append("    policyid: ").append(toIndentedString(policyid)).append("\n");
    sb.append("    delegateAdmin: ").append(toIndentedString(delegateAdmin)).append("\n");
    sb.append("    itemType: ").append(toIndentedString(itemType)).append("\n");
    sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

