/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.JsonRangerBaseModelObject;
import io.swagger.client.model.JsonRoleMember;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class JsonRangerRole extends JsonRangerBaseModelObject {
  @SerializedName("createdByUser")
  private String createdByUser = null;

  @SerializedName("groups")
  private List<JsonRoleMember> groups = null;

  @SerializedName("users")
  private List<JsonRoleMember> users = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("options")
  private Map<String, Object> options = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("roles")
  private List<JsonRoleMember> roles = null;

  public JsonRangerRole createdByUser(String createdByUser) {
    this.createdByUser = createdByUser;
    return this;
  }

   /**
   * 
   * @return createdByUser
  **/
  @ApiModelProperty(value = "")
  public String getCreatedByUser() {
    return createdByUser;
  }

  public void setCreatedByUser(String createdByUser) {
    this.createdByUser = createdByUser;
  }

  public JsonRangerRole groups(List<JsonRoleMember> groups) {
    this.groups = groups;
    return this;
  }

  public JsonRangerRole addGroupsItem(JsonRoleMember groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<JsonRoleMember>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * 
   * @return groups
  **/
  @ApiModelProperty(value = "")
  public List<JsonRoleMember> getGroups() {
    return groups;
  }

  public void setGroups(List<JsonRoleMember> groups) {
    this.groups = groups;
  }

  public JsonRangerRole users(List<JsonRoleMember> users) {
    this.users = users;
    return this;
  }

  public JsonRangerRole addUsersItem(JsonRoleMember usersItem) {
    if (this.users == null) {
      this.users = new ArrayList<JsonRoleMember>();
    }
    this.users.add(usersItem);
    return this;
  }

   /**
   * 
   * @return users
  **/
  @ApiModelProperty(value = "")
  public List<JsonRoleMember> getUsers() {
    return users;
  }

  public void setUsers(List<JsonRoleMember> users) {
    this.users = users;
  }

  public JsonRangerRole name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public JsonRangerRole options(Map<String, Object> options) {
    this.options = options;
    return this;
  }

  public JsonRangerRole putOptionsItem(String key, Object optionsItem) {
    if (this.options == null) {
      this.options = new HashMap<String, Object>();
    }
    this.options.put(key, optionsItem);
    return this;
  }

   /**
   * 
   * @return options
  **/
  @ApiModelProperty(value = "")
  public Map<String, Object> getOptions() {
    return options;
  }

  public void setOptions(Map<String, Object> options) {
    this.options = options;
  }

  public JsonRangerRole description(String description) {
    this.description = description;
    return this;
  }

   /**
   * 
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public JsonRangerRole roles(List<JsonRoleMember> roles) {
    this.roles = roles;
    return this;
  }

  public JsonRangerRole addRolesItem(JsonRoleMember rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<JsonRoleMember>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * 
   * @return roles
  **/
  @ApiModelProperty(value = "")
  public List<JsonRoleMember> getRoles() {
    return roles;
  }

  public void setRoles(List<JsonRoleMember> roles) {
    this.roles = roles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonRangerRole jsonRangerRole = (JsonRangerRole) o;
    return Objects.equals(this.createdByUser, jsonRangerRole.createdByUser) &&
        Objects.equals(this.groups, jsonRangerRole.groups) &&
        Objects.equals(this.users, jsonRangerRole.users) &&
        Objects.equals(this.name, jsonRangerRole.name) &&
        Objects.equals(this.options, jsonRangerRole.options) &&
        Objects.equals(this.description, jsonRangerRole.description) &&
        Objects.equals(this.roles, jsonRangerRole.roles) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdByUser, groups, users, name, options, description, roles, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonRangerRole {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    createdByUser: ").append(toIndentedString(createdByUser)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

