/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.JsonXXDBBase;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class JsonXXAccessTypeDefGrants extends JsonXXDBBase {
  @SerializedName("id")
  private BigDecimal id = null;

  @SerializedName("atdId")
  private BigDecimal atdId = null;

  @SerializedName("impliedGrant")
  private String impliedGrant = null;

  public JsonXXAccessTypeDefGrants id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;id&lt;/b&gt;
   * @return id
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>id</b>")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public JsonXXAccessTypeDefGrants atdId(BigDecimal atdId) {
    this.atdId = atdId;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;atdId&lt;/b&gt;
   * @return atdId
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>atdId</b>")
  public BigDecimal getAtdId() {
    return atdId;
  }

  public void setAtdId(BigDecimal atdId) {
    this.atdId = atdId;
  }

  public JsonXXAccessTypeDefGrants impliedGrant(String impliedGrant) {
    this.impliedGrant = impliedGrant;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;impliedGrant&lt;/b&gt;
   * @return impliedGrant
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>impliedGrant</b>")
  public String getImpliedGrant() {
    return impliedGrant;
  }

  public void setImpliedGrant(String impliedGrant) {
    this.impliedGrant = impliedGrant;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonXXAccessTypeDefGrants jsonXXAccessTypeDefGrants = (JsonXXAccessTypeDefGrants) o;
    return Objects.equals(this.id, jsonXXAccessTypeDefGrants.id) &&
        Objects.equals(this.atdId, jsonXXAccessTypeDefGrants.atdId) &&
        Objects.equals(this.impliedGrant, jsonXXAccessTypeDefGrants.impliedGrant) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, atdId, impliedGrant, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonXXAccessTypeDefGrants {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    atdId: ").append(toIndentedString(atdId)).append("\n");
    sb.append("    impliedGrant: ").append(toIndentedString(impliedGrant)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

