/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.JsonVXDataObject;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class JsonVXRepository extends JsonVXDataObject {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("repositoryType")
  private String repositoryType = null;

  @SerializedName("config")
  private String config = null;

  @SerializedName("isActive")
  private Boolean isActive = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("myClassType")
  private Integer myClassType = null;

  public JsonVXRepository name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;name&lt;/b&gt;
   * @return name
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>name</b>")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public JsonVXRepository description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;description&lt;/b&gt;
   * @return description
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>description</b>")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public JsonVXRepository repositoryType(String repositoryType) {
    this.repositoryType = repositoryType;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;repositoryType&lt;/b&gt;
   * @return repositoryType
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>repositoryType</b>")
  public String getRepositoryType() {
    return repositoryType;
  }

  public void setRepositoryType(String repositoryType) {
    this.repositoryType = repositoryType;
  }

  public JsonVXRepository config(String config) {
    this.config = config;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;config&lt;/b&gt;
   * @return config
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>config</b>")
  public String getConfig() {
    return config;
  }

  public void setConfig(String config) {
    this.config = config;
  }

  public JsonVXRepository isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;isActive&lt;/b&gt;
   * @return isActive
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>isActive</b>")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public JsonVXRepository version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;version&lt;/b&gt;
   * @return version
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>version</b>")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public JsonVXRepository myClassType(Integer myClassType) {
    this.myClassType = myClassType;
    return this;
  }

   /**
   * 
   * @return myClassType
  **/
  @ApiModelProperty(value = "")
  public Integer getMyClassType() {
    return myClassType;
  }

  public void setMyClassType(Integer myClassType) {
    this.myClassType = myClassType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonVXRepository jsonVXRepository = (JsonVXRepository) o;
    return Objects.equals(this.name, jsonVXRepository.name) &&
        Objects.equals(this.description, jsonVXRepository.description) &&
        Objects.equals(this.repositoryType, jsonVXRepository.repositoryType) &&
        Objects.equals(this.config, jsonVXRepository.config) &&
        Objects.equals(this.isActive, jsonVXRepository.isActive) &&
        Objects.equals(this.version, jsonVXRepository.version) &&
        Objects.equals(this.myClassType, jsonVXRepository.myClassType) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, repositoryType, config, isActive, version, myClassType, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonVXRepository {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    repositoryType: ").append(toIndentedString(repositoryType)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    myClassType: ").append(toIndentedString(myClassType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

