/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.JsonRangerRole;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class JsonRangerRoles {
  @SerializedName("roleVersion")
  private BigDecimal roleVersion = null;

  @SerializedName("serviceName")
  private String serviceName = null;

  @SerializedName("roleUpdateTime")
  private BigDecimal roleUpdateTime = null;

  @SerializedName("rangerRoles")
  private List<JsonRangerRole> rangerRoles = null;

  public JsonRangerRoles roleVersion(BigDecimal roleVersion) {
    this.roleVersion = roleVersion;
    return this;
  }

   /**
   * 
   * @return roleVersion
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getRoleVersion() {
    return roleVersion;
  }

  public void setRoleVersion(BigDecimal roleVersion) {
    this.roleVersion = roleVersion;
  }

  public JsonRangerRoles serviceName(String serviceName) {
    this.serviceName = serviceName;
    return this;
  }

   /**
   * 
   * @return serviceName
  **/
  @ApiModelProperty(value = "")
  public String getServiceName() {
    return serviceName;
  }

  public void setServiceName(String serviceName) {
    this.serviceName = serviceName;
  }

  public JsonRangerRoles roleUpdateTime(BigDecimal roleUpdateTime) {
    this.roleUpdateTime = roleUpdateTime;
    return this;
  }

   /**
   * 
   * @return roleUpdateTime
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getRoleUpdateTime() {
    return roleUpdateTime;
  }

  public void setRoleUpdateTime(BigDecimal roleUpdateTime) {
    this.roleUpdateTime = roleUpdateTime;
  }

  public JsonRangerRoles rangerRoles(List<JsonRangerRole> rangerRoles) {
    this.rangerRoles = rangerRoles;
    return this;
  }

  public JsonRangerRoles addRangerRolesItem(JsonRangerRole rangerRolesItem) {
    if (this.rangerRoles == null) {
      this.rangerRoles = new ArrayList<JsonRangerRole>();
    }
    this.rangerRoles.add(rangerRolesItem);
    return this;
  }

   /**
   * 
   * @return rangerRoles
  **/
  @ApiModelProperty(value = "")
  public List<JsonRangerRole> getRangerRoles() {
    return rangerRoles;
  }

  public void setRangerRoles(List<JsonRangerRole> rangerRoles) {
    this.rangerRoles = rangerRoles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonRangerRoles jsonRangerRoles = (JsonRangerRoles) o;
    return Objects.equals(this.roleVersion, jsonRangerRoles.roleVersion) &&
        Objects.equals(this.serviceName, jsonRangerRoles.serviceName) &&
        Objects.equals(this.roleUpdateTime, jsonRangerRoles.roleUpdateTime) &&
        Objects.equals(this.rangerRoles, jsonRangerRoles.rangerRoles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roleVersion, serviceName, roleUpdateTime, rangerRoles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonRangerRoles {\n");
    
    sb.append("    roleVersion: ").append(toIndentedString(roleVersion)).append("\n");
    sb.append("    serviceName: ").append(toIndentedString(serviceName)).append("\n");
    sb.append("    roleUpdateTime: ").append(toIndentedString(roleUpdateTime)).append("\n");
    sb.append("    rangerRoles: ").append(toIndentedString(rangerRoles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

