/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.JsonXXDBBase;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class JsonXXAuthSession extends JsonXXDBBase {
  @SerializedName("id")
  private BigDecimal id = null;

  @SerializedName("myClassType")
  private Integer myClassType = null;

  @SerializedName("loginId")
  private String loginId = null;

  @SerializedName("userId")
  private BigDecimal userId = null;

  @SerializedName("extSessionId")
  private String extSessionId = null;

  @SerializedName("authTime")
  private BigDecimal authTime = null;

  @SerializedName("authStatus")
  private Integer authStatus = null;

  @SerializedName("authType")
  private Integer authType = null;

  @SerializedName("authProvider")
  private Integer authProvider = null;

  @SerializedName("deviceType")
  private Integer deviceType = null;

  @SerializedName("requestIP")
  private String requestIP = null;

  @SerializedName("requestUserAgent")
  private String requestUserAgent = null;

  public JsonXXAuthSession id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;id&lt;/b&gt;
   * @return id
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>id</b>")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public JsonXXAuthSession myClassType(Integer myClassType) {
    this.myClassType = myClassType;
    return this;
  }

   /**
   * 
   * @return myClassType
  **/
  @ApiModelProperty(value = "")
  public Integer getMyClassType() {
    return myClassType;
  }

  public void setMyClassType(Integer myClassType) {
    this.myClassType = myClassType;
  }

  public JsonXXAuthSession loginId(String loginId) {
    this.loginId = loginId;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;loginId&lt;/b&gt;
   * @return loginId
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>loginId</b>")
  public String getLoginId() {
    return loginId;
  }

  public void setLoginId(String loginId) {
    this.loginId = loginId;
  }

  public JsonXXAuthSession userId(BigDecimal userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;userId&lt;/b&gt;
   * @return userId
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>userId</b>")
  public BigDecimal getUserId() {
    return userId;
  }

  public void setUserId(BigDecimal userId) {
    this.userId = userId;
  }

  public JsonXXAuthSession extSessionId(String extSessionId) {
    this.extSessionId = extSessionId;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;extSessionId&lt;/b&gt;
   * @return extSessionId
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>extSessionId</b>")
  public String getExtSessionId() {
    return extSessionId;
  }

  public void setExtSessionId(String extSessionId) {
    this.extSessionId = extSessionId;
  }

  public JsonXXAuthSession authTime(BigDecimal authTime) {
    this.authTime = authTime;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;authTime&lt;/b&gt;
   * @return authTime
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>authTime</b>")
  public BigDecimal getAuthTime() {
    return authTime;
  }

  public void setAuthTime(BigDecimal authTime) {
    this.authTime = authTime;
  }

  public JsonXXAuthSession authStatus(Integer authStatus) {
    this.authStatus = authStatus;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;authStatus&lt;/b&gt;
   * @return authStatus
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>authStatus</b>")
  public Integer getAuthStatus() {
    return authStatus;
  }

  public void setAuthStatus(Integer authStatus) {
    this.authStatus = authStatus;
  }

  public JsonXXAuthSession authType(Integer authType) {
    this.authType = authType;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;authType&lt;/b&gt;
   * @return authType
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>authType</b>")
  public Integer getAuthType() {
    return authType;
  }

  public void setAuthType(Integer authType) {
    this.authType = authType;
  }

  public JsonXXAuthSession authProvider(Integer authProvider) {
    this.authProvider = authProvider;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;authProvider&lt;/b&gt;
   * @return authProvider
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>authProvider</b>")
  public Integer getAuthProvider() {
    return authProvider;
  }

  public void setAuthProvider(Integer authProvider) {
    this.authProvider = authProvider;
  }

  public JsonXXAuthSession deviceType(Integer deviceType) {
    this.deviceType = deviceType;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;deviceType&lt;/b&gt;
   * @return deviceType
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>deviceType</b>")
  public Integer getDeviceType() {
    return deviceType;
  }

  public void setDeviceType(Integer deviceType) {
    this.deviceType = deviceType;
  }

  public JsonXXAuthSession requestIP(String requestIP) {
    this.requestIP = requestIP;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;requestIP&lt;/b&gt;
   * @return requestIP
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>requestIP</b>")
  public String getRequestIP() {
    return requestIP;
  }

  public void setRequestIP(String requestIP) {
    this.requestIP = requestIP;
  }

  public JsonXXAuthSession requestUserAgent(String requestUserAgent) {
    this.requestUserAgent = requestUserAgent;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;requestUserAgent&lt;/b&gt;
   * @return requestUserAgent
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>requestUserAgent</b>")
  public String getRequestUserAgent() {
    return requestUserAgent;
  }

  public void setRequestUserAgent(String requestUserAgent) {
    this.requestUserAgent = requestUserAgent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonXXAuthSession jsonXXAuthSession = (JsonXXAuthSession) o;
    return Objects.equals(this.id, jsonXXAuthSession.id) &&
        Objects.equals(this.myClassType, jsonXXAuthSession.myClassType) &&
        Objects.equals(this.loginId, jsonXXAuthSession.loginId) &&
        Objects.equals(this.userId, jsonXXAuthSession.userId) &&
        Objects.equals(this.extSessionId, jsonXXAuthSession.extSessionId) &&
        Objects.equals(this.authTime, jsonXXAuthSession.authTime) &&
        Objects.equals(this.authStatus, jsonXXAuthSession.authStatus) &&
        Objects.equals(this.authType, jsonXXAuthSession.authType) &&
        Objects.equals(this.authProvider, jsonXXAuthSession.authProvider) &&
        Objects.equals(this.deviceType, jsonXXAuthSession.deviceType) &&
        Objects.equals(this.requestIP, jsonXXAuthSession.requestIP) &&
        Objects.equals(this.requestUserAgent, jsonXXAuthSession.requestUserAgent) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, myClassType, loginId, userId, extSessionId, authTime, authStatus, authType, authProvider, deviceType, requestIP, requestUserAgent, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonXXAuthSession {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    myClassType: ").append(toIndentedString(myClassType)).append("\n");
    sb.append("    loginId: ").append(toIndentedString(loginId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    extSessionId: ").append(toIndentedString(extSessionId)).append("\n");
    sb.append("    authTime: ").append(toIndentedString(authTime)).append("\n");
    sb.append("    authStatus: ").append(toIndentedString(authStatus)).append("\n");
    sb.append("    authType: ").append(toIndentedString(authType)).append("\n");
    sb.append("    authProvider: ").append(toIndentedString(authProvider)).append("\n");
    sb.append("    deviceType: ").append(toIndentedString(deviceType)).append("\n");
    sb.append("    requestIP: ").append(toIndentedString(requestIP)).append("\n");
    sb.append("    requestUserAgent: ").append(toIndentedString(requestUserAgent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

