/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.JsonXXDBBase;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class JsonXXServiceResourceElementValue extends JsonXXDBBase {
  @SerializedName("id")
  private BigDecimal id = null;

  @SerializedName("resElementId")
  private BigDecimal resElementId = null;

  @SerializedName("value")
  private String value = null;

  @SerializedName("sortOrder")
  private BigDecimal sortOrder = null;

  @SerializedName("myClassType")
  private Integer myClassType = null;

  public JsonXXServiceResourceElementValue id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;id&lt;/b&gt;
   * @return id
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>id</b>")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public JsonXXServiceResourceElementValue resElementId(BigDecimal resElementId) {
    this.resElementId = resElementId;
    return this;
  }

   /**
   * 
   * @return resElementId
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getResElementId() {
    return resElementId;
  }

  public void setResElementId(BigDecimal resElementId) {
    this.resElementId = resElementId;
  }

  public JsonXXServiceResourceElementValue value(String value) {
    this.value = value;
    return this;
  }

   /**
   * 
   * @return value
  **/
  @ApiModelProperty(value = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public JsonXXServiceResourceElementValue sortOrder(BigDecimal sortOrder) {
    this.sortOrder = sortOrder;
    return this;
  }

   /**
   * 
   * @return sortOrder
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getSortOrder() {
    return sortOrder;
  }

  public void setSortOrder(BigDecimal sortOrder) {
    this.sortOrder = sortOrder;
  }

  public JsonXXServiceResourceElementValue myClassType(Integer myClassType) {
    this.myClassType = myClassType;
    return this;
  }

   /**
   * 
   * @return myClassType
  **/
  @ApiModelProperty(value = "")
  public Integer getMyClassType() {
    return myClassType;
  }

  public void setMyClassType(Integer myClassType) {
    this.myClassType = myClassType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonXXServiceResourceElementValue jsonXXServiceResourceElementValue = (JsonXXServiceResourceElementValue) o;
    return Objects.equals(this.id, jsonXXServiceResourceElementValue.id) &&
        Objects.equals(this.resElementId, jsonXXServiceResourceElementValue.resElementId) &&
        Objects.equals(this.value, jsonXXServiceResourceElementValue.value) &&
        Objects.equals(this.sortOrder, jsonXXServiceResourceElementValue.sortOrder) &&
        Objects.equals(this.myClassType, jsonXXServiceResourceElementValue.myClassType) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, resElementId, value, sortOrder, myClassType, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonXXServiceResourceElementValue {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    resElementId: ").append(toIndentedString(resElementId)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    sortOrder: ").append(toIndentedString(sortOrder)).append("\n");
    sb.append("    myClassType: ").append(toIndentedString(myClassType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

