/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.JsonXXDBBase;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class JsonXXTrxLog extends JsonXXDBBase {
  @SerializedName("id")
  private BigDecimal id = null;

  @SerializedName("myClassType")
  private Integer myClassType = null;

  @SerializedName("objectClassType")
  private Integer objectClassType = null;

  @SerializedName("objectId")
  private BigDecimal objectId = null;

  @SerializedName("parentObjectId")
  private BigDecimal parentObjectId = null;

  @SerializedName("parentObjectClassType")
  private Integer parentObjectClassType = null;

  @SerializedName("parentObjectName")
  private String parentObjectName = null;

  @SerializedName("objectName")
  private String objectName = null;

  @SerializedName("attributeName")
  private String attributeName = null;

  @SerializedName("previousValue")
  private String previousValue = null;

  @SerializedName("newValue")
  private String newValue = null;

  @SerializedName("transactionId")
  private String transactionId = null;

  @SerializedName("action")
  private String action = null;

  @SerializedName("sessionId")
  private String sessionId = null;

  @SerializedName("requestId")
  private String requestId = null;

  @SerializedName("sessionType")
  private String sessionType = null;

  public JsonXXTrxLog id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;id&lt;/b&gt;
   * @return id
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>id</b>")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public JsonXXTrxLog myClassType(Integer myClassType) {
    this.myClassType = myClassType;
    return this;
  }

   /**
   * 
   * @return myClassType
  **/
  @ApiModelProperty(value = "")
  public Integer getMyClassType() {
    return myClassType;
  }

  public void setMyClassType(Integer myClassType) {
    this.myClassType = myClassType;
  }

  public JsonXXTrxLog objectClassType(Integer objectClassType) {
    this.objectClassType = objectClassType;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;objectClassType&lt;/b&gt;
   * @return objectClassType
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>objectClassType</b>")
  public Integer getObjectClassType() {
    return objectClassType;
  }

  public void setObjectClassType(Integer objectClassType) {
    this.objectClassType = objectClassType;
  }

  public JsonXXTrxLog objectId(BigDecimal objectId) {
    this.objectId = objectId;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;objectId&lt;/b&gt;
   * @return objectId
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>objectId</b>")
  public BigDecimal getObjectId() {
    return objectId;
  }

  public void setObjectId(BigDecimal objectId) {
    this.objectId = objectId;
  }

  public JsonXXTrxLog parentObjectId(BigDecimal parentObjectId) {
    this.parentObjectId = parentObjectId;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;parentObjectId&lt;/b&gt;
   * @return parentObjectId
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>parentObjectId</b>")
  public BigDecimal getParentObjectId() {
    return parentObjectId;
  }

  public void setParentObjectId(BigDecimal parentObjectId) {
    this.parentObjectId = parentObjectId;
  }

  public JsonXXTrxLog parentObjectClassType(Integer parentObjectClassType) {
    this.parentObjectClassType = parentObjectClassType;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;parentObjectClassType&lt;/b&gt;
   * @return parentObjectClassType
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>parentObjectClassType</b>")
  public Integer getParentObjectClassType() {
    return parentObjectClassType;
  }

  public void setParentObjectClassType(Integer parentObjectClassType) {
    this.parentObjectClassType = parentObjectClassType;
  }

  public JsonXXTrxLog parentObjectName(String parentObjectName) {
    this.parentObjectName = parentObjectName;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;parentObjectName&lt;/b&gt;
   * @return parentObjectName
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>parentObjectName</b>")
  public String getParentObjectName() {
    return parentObjectName;
  }

  public void setParentObjectName(String parentObjectName) {
    this.parentObjectName = parentObjectName;
  }

  public JsonXXTrxLog objectName(String objectName) {
    this.objectName = objectName;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;objectName&lt;/b&gt;
   * @return objectName
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>objectName</b>")
  public String getObjectName() {
    return objectName;
  }

  public void setObjectName(String objectName) {
    this.objectName = objectName;
  }

  public JsonXXTrxLog attributeName(String attributeName) {
    this.attributeName = attributeName;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;attributeName&lt;/b&gt;
   * @return attributeName
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>attributeName</b>")
  public String getAttributeName() {
    return attributeName;
  }

  public void setAttributeName(String attributeName) {
    this.attributeName = attributeName;
  }

  public JsonXXTrxLog previousValue(String previousValue) {
    this.previousValue = previousValue;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;previousValue&lt;/b&gt;
   * @return previousValue
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>previousValue</b>")
  public String getPreviousValue() {
    return previousValue;
  }

  public void setPreviousValue(String previousValue) {
    this.previousValue = previousValue;
  }

  public JsonXXTrxLog newValue(String newValue) {
    this.newValue = newValue;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;newValue&lt;/b&gt;
   * @return newValue
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>newValue</b>")
  public String getNewValue() {
    return newValue;
  }

  public void setNewValue(String newValue) {
    this.newValue = newValue;
  }

  public JsonXXTrxLog transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;transactionId&lt;/b&gt;
   * @return transactionId
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>transactionId</b>")
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public JsonXXTrxLog action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;action&lt;/b&gt;
   * @return action
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>action</b>")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public JsonXXTrxLog sessionId(String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;sessionId&lt;/b&gt;
   * @return sessionId
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>sessionId</b>")
  public String getSessionId() {
    return sessionId;
  }

  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }

  public JsonXXTrxLog requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;requestId&lt;/b&gt;
   * @return requestId
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>requestId</b>")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public JsonXXTrxLog sessionType(String sessionType) {
    this.sessionType = sessionType;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;sessionType&lt;/b&gt;
   * @return sessionType
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>sessionType</b>")
  public String getSessionType() {
    return sessionType;
  }

  public void setSessionType(String sessionType) {
    this.sessionType = sessionType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonXXTrxLog jsonXXTrxLog = (JsonXXTrxLog) o;
    return Objects.equals(this.id, jsonXXTrxLog.id) &&
        Objects.equals(this.myClassType, jsonXXTrxLog.myClassType) &&
        Objects.equals(this.objectClassType, jsonXXTrxLog.objectClassType) &&
        Objects.equals(this.objectId, jsonXXTrxLog.objectId) &&
        Objects.equals(this.parentObjectId, jsonXXTrxLog.parentObjectId) &&
        Objects.equals(this.parentObjectClassType, jsonXXTrxLog.parentObjectClassType) &&
        Objects.equals(this.parentObjectName, jsonXXTrxLog.parentObjectName) &&
        Objects.equals(this.objectName, jsonXXTrxLog.objectName) &&
        Objects.equals(this.attributeName, jsonXXTrxLog.attributeName) &&
        Objects.equals(this.previousValue, jsonXXTrxLog.previousValue) &&
        Objects.equals(this.newValue, jsonXXTrxLog.newValue) &&
        Objects.equals(this.transactionId, jsonXXTrxLog.transactionId) &&
        Objects.equals(this.action, jsonXXTrxLog.action) &&
        Objects.equals(this.sessionId, jsonXXTrxLog.sessionId) &&
        Objects.equals(this.requestId, jsonXXTrxLog.requestId) &&
        Objects.equals(this.sessionType, jsonXXTrxLog.sessionType) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, myClassType, objectClassType, objectId, parentObjectId, parentObjectClassType, parentObjectName, objectName, attributeName, previousValue, newValue, transactionId, action, sessionId, requestId, sessionType, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonXXTrxLog {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    myClassType: ").append(toIndentedString(myClassType)).append("\n");
    sb.append("    objectClassType: ").append(toIndentedString(objectClassType)).append("\n");
    sb.append("    objectId: ").append(toIndentedString(objectId)).append("\n");
    sb.append("    parentObjectId: ").append(toIndentedString(parentObjectId)).append("\n");
    sb.append("    parentObjectClassType: ").append(toIndentedString(parentObjectClassType)).append("\n");
    sb.append("    parentObjectName: ").append(toIndentedString(parentObjectName)).append("\n");
    sb.append("    objectName: ").append(toIndentedString(objectName)).append("\n");
    sb.append("    attributeName: ").append(toIndentedString(attributeName)).append("\n");
    sb.append("    previousValue: ").append(toIndentedString(previousValue)).append("\n");
    sb.append("    newValue: ").append(toIndentedString(newValue)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    sessionType: ").append(toIndentedString(sessionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

