/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.XmlNs0VXDataObject;
import io.swagger.client.model.XmlNs0VXGroup;
import io.swagger.client.model.XmlNs0VXUser;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class XmlNs0VXGroupUserInfo extends XmlNs0VXDataObject {
  @SerializedName("xgroupInfo")
  private XmlNs0VXGroup xgroupInfo = null;

  @SerializedName("xuserInfo")
  private List<XmlNs0VXUser> xuserInfo = null;

  public XmlNs0VXGroupUserInfo xgroupInfo(XmlNs0VXGroup xgroupInfo) {
    this.xgroupInfo = xgroupInfo;
    return this;
  }

   /**
   * Get xgroupInfo
   * @return xgroupInfo
  **/
  @ApiModelProperty(value = "")
  public XmlNs0VXGroup getXgroupInfo() {
    return xgroupInfo;
  }

  public void setXgroupInfo(XmlNs0VXGroup xgroupInfo) {
    this.xgroupInfo = xgroupInfo;
  }

  public XmlNs0VXGroupUserInfo xuserInfo(List<XmlNs0VXUser> xuserInfo) {
    this.xuserInfo = xuserInfo;
    return this;
  }

  public XmlNs0VXGroupUserInfo addXuserInfoItem(XmlNs0VXUser xuserInfoItem) {
    if (this.xuserInfo == null) {
      this.xuserInfo = new ArrayList<XmlNs0VXUser>();
    }
    this.xuserInfo.add(xuserInfoItem);
    return this;
  }

   /**
   * 
   * @return xuserInfo
  **/
  @ApiModelProperty(value = "")
  public List<XmlNs0VXUser> getXuserInfo() {
    return xuserInfo;
  }

  public void setXuserInfo(List<XmlNs0VXUser> xuserInfo) {
    this.xuserInfo = xuserInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XmlNs0VXGroupUserInfo xmlNs0VXGroupUserInfo = (XmlNs0VXGroupUserInfo) o;
    return Objects.equals(this.xgroupInfo, xmlNs0VXGroupUserInfo.xgroupInfo) &&
        Objects.equals(this.xuserInfo, xmlNs0VXGroupUserInfo.xuserInfo) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(xgroupInfo, xuserInfo, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class XmlNs0VXGroupUserInfo {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    xgroupInfo: ").append(toIndentedString(xgroupInfo)).append("\n");
    sb.append("    xuserInfo: ").append(toIndentedString(xuserInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

