/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.XmlNs0XXDBBase;
import java.io.IOException;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class XmlNs0XXServiceResourceElementValue extends XmlNs0XXDBBase {
  @SerializedName("resElementId")
  private Long resElementId = null;

  @SerializedName("sortOrder")
  private Integer sortOrder = null;

  @SerializedName("value")
  private String value = null;

  public XmlNs0XXServiceResourceElementValue resElementId(Long resElementId) {
    this.resElementId = resElementId;
    return this;
  }

   /**
   * the resElementId
   * @return resElementId
  **/
  @ApiModelProperty(value = "the resElementId")
  public Long getResElementId() {
    return resElementId;
  }

  public void setResElementId(Long resElementId) {
    this.resElementId = resElementId;
  }

  public XmlNs0XXServiceResourceElementValue sortOrder(Integer sortOrder) {
    this.sortOrder = sortOrder;
    return this;
  }

   /**
   * the sortOrder
   * @return sortOrder
  **/
  @ApiModelProperty(value = "the sortOrder")
  public Integer getSortOrder() {
    return sortOrder;
  }

  public void setSortOrder(Integer sortOrder) {
    this.sortOrder = sortOrder;
  }

  public XmlNs0XXServiceResourceElementValue value(String value) {
    this.value = value;
    return this;
  }

   /**
   * the value
   * @return value
  **/
  @ApiModelProperty(value = "the value")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XmlNs0XXServiceResourceElementValue xmlNs0XXServiceResourceElementValue = (XmlNs0XXServiceResourceElementValue) o;
    return Objects.equals(this.resElementId, xmlNs0XXServiceResourceElementValue.resElementId) &&
        Objects.equals(this.sortOrder, xmlNs0XXServiceResourceElementValue.sortOrder) &&
        Objects.equals(this.value, xmlNs0XXServiceResourceElementValue.value) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resElementId, sortOrder, value, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class XmlNs0XXServiceResourceElementValue {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    resElementId: ").append(toIndentedString(resElementId)).append("\n");
    sb.append("    sortOrder: ").append(toIndentedString(sortOrder)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

