/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.XmlNs0XXDBBase;
import java.io.IOException;

/**
 * The persistent class for the x_policy_ref_role database table.
 */
@ApiModel(description = "The persistent class for the x_policy_ref_role database table.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class XmlNs0XXPolicyRefRole extends XmlNs0XXDBBase {
  @SerializedName("policyId")
  private Long policyId = null;

  @SerializedName("roleId")
  private Long roleId = null;

  @SerializedName("roleName")
  private String roleName = null;

  public XmlNs0XXPolicyRefRole policyId(Long policyId) {
    this.policyId = policyId;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;policyId&lt;/b&gt;
   * @return policyId
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>policyId</b>")
  public Long getPolicyId() {
    return policyId;
  }

  public void setPolicyId(Long policyId) {
    this.policyId = policyId;
  }

  public XmlNs0XXPolicyRefRole roleId(Long roleId) {
    this.roleId = roleId;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;roleId&lt;/b&gt;
   * @return roleId
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>roleId</b>")
  public Long getRoleId() {
    return roleId;
  }

  public void setRoleId(Long roleId) {
    this.roleId = roleId;
  }

  public XmlNs0XXPolicyRefRole roleName(String roleName) {
    this.roleName = roleName;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;roleName&lt;/b&gt;
   * @return roleName
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>roleName</b>")
  public String getRoleName() {
    return roleName;
  }

  public void setRoleName(String roleName) {
    this.roleName = roleName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XmlNs0XXPolicyRefRole xmlNs0XXPolicyRefRole = (XmlNs0XXPolicyRefRole) o;
    return Objects.equals(this.policyId, xmlNs0XXPolicyRefRole.policyId) &&
        Objects.equals(this.roleId, xmlNs0XXPolicyRefRole.roleId) &&
        Objects.equals(this.roleName, xmlNs0XXPolicyRefRole.roleName) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(policyId, roleId, roleName, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class XmlNs0XXPolicyRefRole {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("    roleId: ").append(toIndentedString(roleId)).append("\n");
    sb.append("    roleName: ").append(toIndentedString(roleName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

