/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.XmlNs0XXDBBase;
import java.io.IOException;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class XmlNs0XXSecurityZoneRefGroup extends XmlNs0XXDBBase {
  @SerializedName("groupId")
  private Long groupId = null;

  @SerializedName("groupName")
  private String groupName = null;

  @SerializedName("zoneId")
  private Long zoneId = null;

  public XmlNs0XXSecurityZoneRefGroup groupId(Long groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;groupId&lt;/b&gt;
   * @return groupId
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>groupId</b>")
  public Long getGroupId() {
    return groupId;
  }

  public void setGroupId(Long groupId) {
    this.groupId = groupId;
  }

  public XmlNs0XXSecurityZoneRefGroup groupName(String groupName) {
    this.groupName = groupName;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;groupName&lt;/b&gt;
   * @return groupName
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>groupName</b>")
  public String getGroupName() {
    return groupName;
  }

  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  public XmlNs0XXSecurityZoneRefGroup zoneId(Long zoneId) {
    this.zoneId = zoneId;
    return this;
  }

   /**
   * Returns the value for the member attribute &lt;b&gt;zoneId&lt;/b&gt;
   * @return zoneId
  **/
  @ApiModelProperty(value = "Returns the value for the member attribute <b>zoneId</b>")
  public Long getZoneId() {
    return zoneId;
  }

  public void setZoneId(Long zoneId) {
    this.zoneId = zoneId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XmlNs0XXSecurityZoneRefGroup xmlNs0XXSecurityZoneRefGroup = (XmlNs0XXSecurityZoneRefGroup) o;
    return Objects.equals(this.groupId, xmlNs0XXSecurityZoneRefGroup.groupId) &&
        Objects.equals(this.groupName, xmlNs0XXSecurityZoneRefGroup.groupName) &&
        Objects.equals(this.zoneId, xmlNs0XXSecurityZoneRefGroup.zoneId) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupId, groupName, zoneId, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class XmlNs0XXSecurityZoneRefGroup {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    zoneId: ").append(toIndentedString(zoneId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

