/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.XmlNs0VXDataObject;
import java.io.IOException;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T15:05:51.243Z")
public class XmlNs0VXKmsKey extends XmlNs0VXDataObject {
  @SerializedName("attributes")
  private Object attributes = null;

  @SerializedName("cipher")
  private String cipher = null;

  @SerializedName("created")
  private Long created = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("length")
  private Integer length = null;

  @SerializedName("material")
  private String material = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("versionName")
  private String versionName = null;

  @SerializedName("versions")
  private Integer versions = null;

  public XmlNs0VXKmsKey attributes(Object attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * the attributes
   * @return attributes
  **/
  @ApiModelProperty(value = "the attributes")
  public Object getAttributes() {
    return attributes;
  }

  public void setAttributes(Object attributes) {
    this.attributes = attributes;
  }

  public XmlNs0VXKmsKey cipher(String cipher) {
    this.cipher = cipher;
    return this;
  }

   /**
   * the cipher
   * @return cipher
  **/
  @ApiModelProperty(value = "the cipher")
  public String getCipher() {
    return cipher;
  }

  public void setCipher(String cipher) {
    this.cipher = cipher;
  }

  public XmlNs0VXKmsKey created(Long created) {
    this.created = created;
    return this;
  }

   /**
   * the created
   * @return created
  **/
  @ApiModelProperty(value = "the created")
  public Long getCreated() {
    return created;
  }

  public void setCreated(Long created) {
    this.created = created;
  }

  public XmlNs0VXKmsKey description(String description) {
    this.description = description;
    return this;
  }

   /**
   * the description
   * @return description
  **/
  @ApiModelProperty(value = "the description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public XmlNs0VXKmsKey length(Integer length) {
    this.length = length;
    return this;
  }

   /**
   * the length
   * @return length
  **/
  @ApiModelProperty(value = "the length")
  public Integer getLength() {
    return length;
  }

  public void setLength(Integer length) {
    this.length = length;
  }

  public XmlNs0VXKmsKey material(String material) {
    this.material = material;
    return this;
  }

   /**
   * the material
   * @return material
  **/
  @ApiModelProperty(value = "the material")
  public String getMaterial() {
    return material;
  }

  public void setMaterial(String material) {
    this.material = material;
  }

  public XmlNs0VXKmsKey name(String name) {
    this.name = name;
    return this;
  }

   /**
   * the name
   * @return name
  **/
  @ApiModelProperty(value = "the name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public XmlNs0VXKmsKey versionName(String versionName) {
    this.versionName = versionName;
    return this;
  }

   /**
   * the versionName
   * @return versionName
  **/
  @ApiModelProperty(value = "the versionName")
  public String getVersionName() {
    return versionName;
  }

  public void setVersionName(String versionName) {
    this.versionName = versionName;
  }

  public XmlNs0VXKmsKey versions(Integer versions) {
    this.versions = versions;
    return this;
  }

   /**
   * the version
   * @return versions
  **/
  @ApiModelProperty(value = "the version")
  public Integer getVersions() {
    return versions;
  }

  public void setVersions(Integer versions) {
    this.versions = versions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XmlNs0VXKmsKey xmlNs0VXKmsKey = (XmlNs0VXKmsKey) o;
    return Objects.equals(this.attributes, xmlNs0VXKmsKey.attributes) &&
        Objects.equals(this.cipher, xmlNs0VXKmsKey.cipher) &&
        Objects.equals(this.created, xmlNs0VXKmsKey.created) &&
        Objects.equals(this.description, xmlNs0VXKmsKey.description) &&
        Objects.equals(this.length, xmlNs0VXKmsKey.length) &&
        Objects.equals(this.material, xmlNs0VXKmsKey.material) &&
        Objects.equals(this.name, xmlNs0VXKmsKey.name) &&
        Objects.equals(this.versionName, xmlNs0VXKmsKey.versionName) &&
        Objects.equals(this.versions, xmlNs0VXKmsKey.versions) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributes, cipher, created, description, length, material, name, versionName, versions, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class XmlNs0VXKmsKey {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    cipher: ").append(toIndentedString(cipher)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    material: ").append(toIndentedString(material)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    versionName: ").append(toIndentedString(versionName)).append("\n");
    sb.append("    versions: ").append(toIndentedString(versions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

