/*
 * Ranger REST API
 * Apache Ranger is a framework to enable, monitor and manage comprehensive data security across the Hadoop platform. Apache Ranger currently provides a centralized security adminstration, fine grain access control and detailed auditing for user access within Apache Hadoop, Apache Hive, Apache HBase and other Apache components
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.JsonRangerServiceResource;
import io.swagger.client.model.JsonRangerTag;
import io.swagger.client.model.JsonRangerTagDef;
import io.swagger.client.model.JsonRangerTagResourceMap;
import io.swagger.client.model.JsonServiceTags;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TagRestApi
 */
@Ignore
public class TagRestApiTest {

    private final TagRestApi api = new TagRestApi();

    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createServiceResourceTest() throws Exception {
        Boolean updateIfExists = null;
        JsonRangerServiceResource body = null;
        JsonRangerServiceResource response = api.createServiceResource(updateIfExists, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createTagTest() throws Exception {
        Boolean updateIfExists = null;
        JsonRangerTag body = null;
        JsonRangerTag response = api.createTag(updateIfExists, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createTagDefTest() throws Exception {
        Boolean updateIfExists = null;
        JsonRangerTagDef body = null;
        JsonRangerTagDef response = api.createTagDef(updateIfExists, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createTagResourceMapTest() throws Exception {
        Boolean lenient = null;
        String resourceGuid = null;
        String tagGuid = null;
        JsonRangerTagResourceMap response = api.createTagResourceMap(lenient, resourceGuid, tagGuid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteServiceResourceTest() throws Exception {
        Long id = null;
        api.deleteServiceResource(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteServiceResourceByGuidTest() throws Exception {
        String guid = null;
        Boolean deleteReferences = null;
        api.deleteServiceResourceByGuid(guid, deleteReferences);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteTagTest() throws Exception {
        Long id = null;
        api.deleteTag(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteTagByGuidTest() throws Exception {
        String guid = null;
        api.deleteTagByGuid(guid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteTagDefTest() throws Exception {
        Long id = null;
        api.deleteTagDef(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteTagDefByGuidTest() throws Exception {
        String guid = null;
        api.deleteTagDefByGuid(guid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteTagDeltas2Test() throws Exception {
        Integer days = null;
        api.deleteTagDeltas2(days);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteTagResourceMapTest() throws Exception {
        Long id = null;
        api.deleteTagResourceMap(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteTagResourceMapByGuidTest() throws Exception {
        String guid = null;
        api.deleteTagResourceMapByGuid(guid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteTagResourceMap_0Test() throws Exception {
        String resourceGuid = null;
        String tagGuid = null;
        api.deleteTagResourceMap_0(resourceGuid, tagGuid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllServiceResourcesTest() throws Exception {
        List<JsonRangerServiceResource> response = api.getAllServiceResources();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllTagDefsTest() throws Exception {
        List<JsonRangerTagDef> response = api.getAllTagDefs();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllTagResourceMapsTest() throws Exception {
        List<JsonRangerTagResourceMap> response = api.getAllTagResourceMaps();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllTagsTest() throws Exception {
        List<JsonRangerTag> response = api.getAllTags();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getSecureServiceTagsIfUpdatedTest() throws Exception {
        String serviceName = null;
        Long lastActivationTime = null;
        Long lastKnownVersion = null;
        String pluginCapabilities = null;
        String pluginId = null;
        Boolean supportsTagDeltas = null;
        JsonServiceTags response = api.getSecureServiceTagsIfUpdated(serviceName, lastActivationTime, lastKnownVersion, pluginCapabilities, pluginId, supportsTagDeltas);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getServiceResourceTest() throws Exception {
        Long id = null;
        JsonRangerServiceResource response = api.getServiceResource(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getServiceResourceByGuidTest() throws Exception {
        String guid = null;
        JsonRangerServiceResource response = api.getServiceResourceByGuid(guid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getServiceResourceByServiceAndResourceSignatureTest() throws Exception {
        String resourceSignature = null;
        String serviceName = null;
        JsonRangerServiceResource response = api.getServiceResourceByServiceAndResourceSignature(resourceSignature, serviceName);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getServiceResourcesByServiceTest() throws Exception {
        String serviceName = null;
        List<JsonRangerServiceResource> response = api.getServiceResourcesByService(serviceName);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getServiceTagsIfUpdatedTest() throws Exception {
        String serviceName = null;
        Long lastActivationTime = null;
        Long lastKnownVersion = null;
        String pluginCapabilities = null;
        String pluginId = null;
        Boolean supportsTagDeltas = null;
        JsonServiceTags response = api.getServiceTagsIfUpdated(serviceName, lastActivationTime, lastKnownVersion, pluginCapabilities, pluginId, supportsTagDeltas);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTagTest() throws Exception {
        Long id = null;
        JsonRangerTag response = api.getTag(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTagByGuidTest() throws Exception {
        String guid = null;
        JsonRangerTag response = api.getTagByGuid(guid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTagDefTest() throws Exception {
        Long id = null;
        JsonRangerTagDef response = api.getTagDef(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTagDefByGuidTest() throws Exception {
        String guid = null;
        JsonRangerTagDef response = api.getTagDefByGuid(guid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTagDefByNameTest() throws Exception {
        String name = null;
        JsonRangerTagDef response = api.getTagDefByName(name);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTagResourceMapTest() throws Exception {
        String resourceGuid = null;
        String tagGuid = null;
        JsonRangerTagResourceMap response = api.getTagResourceMap(resourceGuid, tagGuid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTagResourceMapByGuidTest() throws Exception {
        String guid = null;
        JsonRangerTagResourceMap response = api.getTagResourceMapByGuid(guid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTagResourceMap_0Test() throws Exception {
        Long id = null;
        JsonRangerTagResourceMap response = api.getTagResourceMap_0(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTagTypesTest() throws Exception {
        List<String> response = api.getTagTypes();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTagsByTypeTest() throws Exception {
        String type = null;
        List<JsonRangerTag> response = api.getTagsByType(type);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void importServiceTagsTest() throws Exception {
        JsonServiceTags body = null;
        api.importServiceTags(body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateServiceResourceTest() throws Exception {
        Long id = null;
        JsonRangerServiceResource body = null;
        JsonRangerServiceResource response = api.updateServiceResource(id, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateServiceResourceByGuidTest() throws Exception {
        String guid = null;
        JsonRangerServiceResource body = null;
        JsonRangerServiceResource response = api.updateServiceResourceByGuid(guid, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateTagTest() throws Exception {
        Long id = null;
        JsonRangerTag body = null;
        JsonRangerTag response = api.updateTag(id, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateTagByGuidTest() throws Exception {
        String guid = null;
        JsonRangerTag body = null;
        JsonRangerTag response = api.updateTagByGuid(guid, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateTagDefTest() throws Exception {
        Long id = null;
        JsonRangerTagDef body = null;
        JsonRangerTagDef response = api.updateTagDef(id, body);

        // TODO: test validations
    }
    
}
